Embeder
DGtal-team/DGtal pull request #1626
Opened 2022-01-07 09:26 UTC by kerautret

# PR Description
New constructor in Point2DEmbedderIn3D to explicitly orient the image plane and new shift method to avoid recomputing orientation plane. It could be useful to improve for instance mesh2heightfield (next PR in DGtalTools).

# Checklist

- [ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [ ] Doxygen documentation of the code completed (classes, methods, types, members...)
- [ ] Documentation module page added or updated.
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug mode.
- [ ] All continuous integration tests pass (Github Actions & appveyor)

2022-01-12 14:45 UTC, kerautret commented
thanks @dcoeurjo your PR looks to have fix the GitHub actions!

2022-01-13 14:21 UTC, dcoeurjo requested changes
Thanks, just a typo

2022-01-13 14:21 UTC, dcoeurjo commented on src/DGtal/kernel/BasicPointFunctors.h
> +                         const typename Point::Component  &anWidth,
```suggestion
                         const typename Point::Component  &aWidth,
```
and in the code

2022-01-13 14:21 UTC, dcoeurjo commented on src/DGtal/kernel/BasicPointFunctors.h
> +                         const Point &anOriginPoint, const typename Space::RealPoint & anNormalVector,
and in the code/doc

2022-01-13 14:22 UTC, kerautret commented
> Thanks, just a typo

Thanks @dcoeurjo done  ;)

2022-01-13 14:24 UTC, dcoeurjo commented on src/DGtal/kernel/BasicPointFunctors.h
> +      uDir2[2] = uDir1[0]*anNormalVector[1]-uDir1[1]*anNormalVector[0];
```suggestion
      uDir2[0] = uDir1[1]*anNormalVector[2]-uDir1[2]*aNormalVector[1];
      uDir2[1] = uDir1[2]*anNormalVector[0]-uDir1[0]*aNormalVector[2];
      uDir2[2] = uDir1[0]*anNormalVector[1]-uDir1[1]*aNormalVector[0];
```

2022-01-13 14:24 UTC, dcoeurjo commented on src/DGtal/kernel/BasicPointFunctors.h
> +      uDir2[2] = uDir1[0]*anNormalVector[1]-uDir1[1]*anNormalVector[0];
+chekc the doc and the  `aWidth`

2022-01-13 14:24 UTC, kerautret commented on src/DGtal/kernel/BasicPointFunctors.h
> +      uDir2[2] = uDir1[0]*anNormalVector[1]-uDir1[1]*anNormalVector[0];
Thanks ;)

2022-02-01 20:06 UTC, dcoeurjo approved these changes

2022-02-01 20:06 UTC, merged

2022-02-01 20:06 UTC, dcoeurjo commented
Thx, merged