Removing imagemagick and using stb_image instead
DGtal-team/DGtal pull request #1648
Opened 2022-06-24 06:59 UTC by dcoeurjo

# PR Description

This PR removes the optional ImageMagick dependency and adds image reader/writer using the stb_image files (included in DGtal).

The image import/export features in jpg, png, bmp and tga are now built-in in DGtal. 

# Checklist

- [ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [ ] Doxygen documentation of the code completed (classes, methods, types, members...)
- [ ] Documentation module page added or updated.
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug mode.
- [ ] All continuous integration tests pass (Github Actions & appveyor)

2022-06-26 12:26 UTC, dcoeurjo commented
ready for review;)

2022-06-26 22:06 UTC, kerautret requested changes
Nice PR! Thanks, just some small suggest and a PR on your branch from another Magick ref to remove

2022-06-26 22:06 UTC, kerautret commented on src/DGtal/io/writers/STBWriter.ih
> + * @file
```suggestion
 * @file STBWriter.ih
```

2022-06-27 06:56 UTC, dcoeurjo commented on src/DGtal/io/readers/GenericReader.h
> +        else if ( extension == "tga" || extension == "jpg" || extension == "png" || extension == "jpeg" || extension == "bmp" )
no you're right. I'd need to add the methods in the Writer class.

2022-06-27 06:56 UTC, dcoeurjo commented on .github/workflows/checkDoxygenDocumentation.sh
> +cd "$SRC_DIR/src/DGtal"
yep, thx

2022-07-01 20:24 UTC, kerautret commented
@dcoeurjo looks fine, and for the gif format ?

2022-07-02 08:06 UTC, dcoeurjo commented
The method is still missing. I'll do it asap. Thx for the review

2022-07-02 12:44 UTC, dcoeurjo commented
Ok gif added in the reader. Thx @kerautret

2022-07-03 14:17 UTC, kerautret approved these changes

2022-07-03 14:22 UTC, merged

2022-07-03 14:26 UTC, dcoeurjo commented
Thx